apiVersion: v1
kind: ConfigMap
metadata:
  name: zookeeper-cm
data:
  ALLOW_ANONYMOUS_LOGIN: "yes"
  ZOO_ADMINSERVER_ENABLED: "false"
  ZOO_AUTOPURGE_PURGEINTERVAL: "2"
  ZOO_AUTOPURGE_SNAPRETAINCOUNT: "10"
  ZOO_CFG_EXTRA: "metricsProvider.className=org.apache.zookeeper.metrics.prometheus.PrometheusMetricsProvider metricsProvider.httpPort=7070"
  ZOO_INIT_LIMIT: "10"
  ZOO_SYNC_LIMIT: "6"
  ZOO_TICK_TIME: "4000"
  ZOO_SERVERS: "server.0=zookeeper-0.zookeeper.datapipeline.svc.cluster.local:2888:3888;2181 server.1=zookeeper-1.zookeeper.datapipeline.svc.cluster.local:2888:3888;2181 server.2=zookeeper-2.zookeeper.datapipeline.svc.cluster.local:2888:3888;2181"